### ISSUE TITLE
wrangler.toml with module workers

### ISSUE THREAD

**Issue by dhrubabasu** [lukeed/cfw#11]
Currently, my `wrangler.toml` needs to include all of these for it to work in `wrangler dev`:

```toml
[build]
command = "yarn run build"

[build.upload]
format = "modules"
dir = "./build"
main = "./index.js"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]
```

It could be good to include some documentation regarding this, took me a while to figure out the `build.upload.rules` part. https://developers.cloudflare.com/workers/cli-wrangler/configuration#buildupload-1
