### ISSUE TITLE
Multiple environments (spanning multiple zone ids)

### ISSUE THREAD

**Issue by dhrubabasu** [lukeed/cfw#8]
My wrangler.toml file looks something like this:

```toml
name = "worker"
type = "javascript"
route = "..."
vars = { ... }

[build]
upload.format = "service-worker"
command = "yarn run build"

[env.qa]
route = "..." # Zone ID 1
vars = { ... }

[env.staging]
route = "..." # Zone ID 2
vars = { ... }

[env.production]
route = "..." # Zone ID 2
vars = { ... }
```

Is there a way to specify different environments, each with their respective settings, in cfw?
